name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build App
      run: xcodebuild -project 'Camera.xcodeproj' -scheme 'Camera' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO